services:
  playlist-synchronizer:
    image: ghcr.io/pkarpovich/playlist-synchronizer:latest
    container_name: playlist-synchronizer
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      DB_PATH: /app/db
      HTTP_PORT: 3200
      SYNC_CONFIG_PATH: /app/sync-config.json
      JOB_CRON_TIME: ${JOB_CRON_TIME}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
    volumes:
      - ./sync-config.json:/app/sync-config.json:ro
      - auth-store:/app/db

volumes:
  auth-store:
