name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.PKG_TOKEN }}
          USERNAME: ${{ github.actor }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        steps:
          - uses: actions/checkout@v3

          - name: Get the version
            id: get_version
            run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2

          - name: set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v2

          - name: build and deploy image to ghcr.io
            env:
              VERSION: ${{ steps.get_version.outputs.VERSION }}
            run: |
              version="$(echo ${VERSION})"
              image_name="$(echo ${REGISTRY}/${IMAGE_NAME})"
              echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
              echo "IMAGE_NAME=${image_name}, VERSION=${version}"
              docker buildx build --push \
                  --platform linux/amd64,linux/arm/v7,linux/arm64 \
                  -t ${image_name}:${version} -t ${image_name}:latest .
