name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.OWNER_TOKEN }}
      NPM_TOKEN: ${{ secrets.OWNER_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.OWNER_TOKEN }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ secrets.PNPM_VERSION }}

      - name: setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: create release pull request / publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm install --frozen-lockfile && pnpm run build && pnpm run publish
          version: pnpm install --frozen-lockfile && pnpm run build && pnpm run version
          title: "chore: update versions"
          commit: "chore: update versions"
